
test:
	npm install
	npm run-script translate quux.js > quux-es5.js
	npm run-script translate import-module.js > import-module-es5.js
	npm run-script translate spread.js > spread-es5.js
	npm run-script translate spread.js | node
